apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  # tls:
  # - hosts:
  #   - jhunufernandes.com.br
  #   # - jhunufernandes
  #   secretName: cafe-secret
  ingressClassName: nginx
  rules:
  # - host: jhunufernandes.com.br
  #   http:
    - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      # - path: /test
      #   pathType: Prefix
      #   backend:
      #     service:
      #       name: nginx
      #       port:
      #         number: 80
  # - host: jhunufernandes
  #   http:
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: nginx
  #           port:
  #             number: 80
  #     - path: /test
  #       pathType: Prefix
  #       backend:
  #         service:
  #           name: nginx
  #           port:
  #             number: 80
